CREATE TABLE `test`.`Emp` ( `Eno` INT NOT NULL AUTO_INCREMENT , `Ename` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , `Sal` FLOAT NOT NULL , `Dept` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , PRIMARY KEY (`Eno`)) ENGINE = InnoDB;


ALTER TABLE `emp` ADD `Email` VARCHAR(50) NOT NULL AFTER `Ename`, ADD `Phon` VARCHAR(20) NOT NULL AFTER `Email`;
